name: Build PwnedBoot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: PwnedBoot.sln
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Install Windows SDK and WDK
      shell: powershell
      run: |
        $webClient = New-Object System.Net.WebClient
        $webClient.DownloadFile("https://go.microsoft.com/fwlink/?linkid=2196240", "wdksetup.exe")
        Start-Process -FilePath "wdksetup.exe" -ArgumentList "/quiet" -Wait

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PwnedBoot
        path: |
          ${{env.GITHUB_WORKSPACE}}/x64/Release/*.dll
          ${{env.GITHUB_WORKSPACE}}/x64/Release/*.pdb
